# Q-Learning (Frozen Lake)
Implementing Markov Decision Process (MDP) in OpenAI-gym's environment, "FrozenLake-v0".
MDP is defined as:
$$Q_{(s,a)} = Q_{(s,a)} + \alpha[R_{(s,a)} + \gamma(\arg \max_{a'} \mathbb{E}(Q_{(s',a')})) - Q_{(s,a)}]$$
where $\mathbb{E}$ is the expected return

### Importing Libraries

In [1]:
import gym
import numpy as np

### Parameters

In [2]:
env = gym.make("FrozenLake-v0")
lr = 0.8 # learning rate
gamma = 0.95 # discount factor
num_episodes = 10000 # total number of episodes

epsilon = 1.0 # exploration rate
max_epsilon = 1.0 
min_epsilon = 0.01
decay_rate = 0.005 # Exponential decay for exploration probability

max_steps = 99 # maximum number of steps in an episode

In [3]:
obs_size = env.observation_space.n # state space size
act_size = env.action_space.n # action space size
q_table = np.zeros(shape=(obs_size, act_size)) # Q(s,a)

### Training Starts

In [4]:
total_rewards = []
for i in range(num_episodes):
    done = False
    s = env.reset() # resetting the environment
    rewards = 0
    
    for j in range(max_steps):
        if np.random.uniform() < epsilon:
            a = env.action_space.sample()
        else:
            a = np.argmax(q_table[s,:])
        
        s1, r, done, _ = env.step(a)
        rewards += r
        
        # Updating Q(s,a) := Q(s,a) + lr * (r + gamme * max Q(s',a') - Q(s,a))
        q_table[s,a] = q_table[s,a] + lr * (r + gamma * np.max(q_table[s1,:]) - q_table[s,a])
        s = s1
        if done:
            break
    total_rewards.append(rewards)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*i)

print(f"Mean Rewards: {np.mean(total_rewards)}")
print(q_table)

Mean Rewards: 0.481
[[4.94516775e-02 5.21610074e-02 4.96585496e-02 5.20754369e-02]
 [4.57377757e-03 2.82504374e-03 2.43040769e-02 4.62734814e-02]
 [4.00933728e-03 1.49580058e-02 6.24570049e-03 2.88932233e-02]
 [3.33051576e-03 1.10577548e-03 3.44539687e-03 2.05349727e-02]
 [6.20192924e-02 1.05187084e-02 4.45745640e-02 2.47123410e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.23470159e-07 4.47087661e-07 1.03648060e-03 8.27040581e-08]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.77972891e-02 8.02003742e-03 4.76025794e-02 6.61519625e-02]
 [1.10402905e-02 3.68646240e-02 2.19531992e-02 3.78872579e-02]
 [1.00050182e-02 1.94214427e-02 9.70403755e-04 9.00712851e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.19268049e-01 1.51767195e-01 3.62854790e-01 6.96852929e-02]
 [2.05442859e-01 3.85004416e-01 1.24462073e-01 8.95022059e-01]
 [0.00000000e+00 0.00000000e+00 0.0